//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""ExampleMap"",
            ""id"": ""3f9e0dc6-57d9-4503-a23a-bdbe5e50929a"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""90866cbe-61ea-42db-8410-ba9d4d06abd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f951dec1-8d3b-4429-be20-89b09d737844"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ExampleMap
        m_ExampleMap = asset.FindActionMap("ExampleMap", throwIfNotFound: true);
        m_ExampleMap_Move = m_ExampleMap.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ExampleMap
    private readonly InputActionMap m_ExampleMap;
    private List<IExampleMapActions> m_ExampleMapActionsCallbackInterfaces = new List<IExampleMapActions>();
    private readonly InputAction m_ExampleMap_Move;
    public struct ExampleMapActions
    {
        private @InputActions m_Wrapper;
        public ExampleMapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_ExampleMap_Move;
        public InputActionMap Get() { return m_Wrapper.m_ExampleMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ExampleMapActions set) { return set.Get(); }
        public void AddCallbacks(IExampleMapActions instance)
        {
            if (instance == null || m_Wrapper.m_ExampleMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ExampleMapActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IExampleMapActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IExampleMapActions instance)
        {
            if (m_Wrapper.m_ExampleMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IExampleMapActions instance)
        {
            foreach (var item in m_Wrapper.m_ExampleMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ExampleMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ExampleMapActions @ExampleMap => new ExampleMapActions(this);
    public interface IExampleMapActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
